name: Node CI

on: [ push ]

env:
  CI: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm

      - run: pnpm install

      - run: pnpm lint
      - run: pnpm test

      - run: pnpm build
      - name: serve static page
        run: pnpm start &

      - uses: cypress-io/github-action@v5

      - name: Setup github pages
        run: echo > public/.nojekyll

      - name: Deploy to github pages
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: public
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
