name: Node CI

on: [ push ]

env:
  CI: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: pnpm install

      - run: pnpm lint
      - run: pnpm test

      - run: pnpm build
      - name: serve static page
        run: pnpm start &

      - uses: cypress-io/github-action@v2

      - name: Setup github pages
        run: echo > public/.nojekyll
      - name: Deploy to github pages
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: public
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
